
all: main.c
	$(CC) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -Wall -o example2 $^ $(LDLIBS) -lrt -lsysrepo

# $(HOME)/hackaton-2017/lede-srv6/build_dir/target-mips_24kc_musl/sysrepo-e4a5705a4c5293ba121048c71899b98243d99edf/ipkg-install/usr/lib/libsysrepo.a \
# ./staging_dir/target-mips_24kc_musl/usr/lib/libyang.so \
# ./staging_dir/target-mips_24kc_musl/usr/lib/libev.a \
# ./staging_dir/target-mips_24kc_musl/usr/lib/libprotobuf-c.a \
# ./staging_dir/target-mips_24kc_musl/usr/lib/libavl.so \
# ./staging_dir/target-mips_24kc_musl/usr/lib/libpcre.a
# 
#  /home/atokar/hackaton-2017/lede-srv6/./staging_dir/target-mips_24kc_musl/usr/lib/libsysrepo.a
